spring:
  datasource:
    url: jdbc:h2:mem:test;NON_KEYWORDS=USER,ORDER,DOSO
    driverClassName: org.h2.Driver
    username: naru
    password: naru0914
    
  h2:
    console:
      enabled: true
      path: /h2-console
  
  sql:
    init:
      mode: always
      data-locations: classpath*:db/import.sql
#      schema-locations: classpath*:db/schema.sql

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          batch_size: 20
        order_inserts: true
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
    
  springdoc:
    swagger-ui:
      groups-order: DESC
      tags-sorter: alpha
      operations-sorter: method
      disable-swagger-default-url: true
      display-request-duration: true
      defaultModelsExpandDepth: 2
      defaultModelExpandDepth: 2
    api-docs:
      path: /api-docs
    show-actuator: true<
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
    writer-with-default-pretty-printer: true
    model-and-view-allowed: true
    paths-to-match:
      - /api/v1/**
        
logging:
  level:
    org.hibernate.SQL: debug 
        
server:
  port: 8080