services:
  # postgresql
  backend-db:
    image: postgres:${POSTGRES_IMAGE_TAG}
    restart: ${RESTART}
    container_name: backend-db
    hostname: backend-db
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - ${backend_DATA:-.}/postgres/pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - TZ
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_INITDB_ARGS
    networks:
      - backend-network
      - external-network
    # restart: always
    restart: unless-stopped

networks:
  backend-network:
    driver: bridge
  external-network:
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"